sudo: required

services:
  - docker

before_install:
  - docker pull obolibrary/oskfull

# command to run tests
# https://github.com/INCATools/ontology-starter-kit/issues/25
script:
  - docker run -v $PWD/:/work -w /work --rm -ti obolibrary/odkfull make test EMAIL_ARGS='-e obo-ci-reports-all@groups.io'

#after_success:
#  coveralls

# whitelist
branches:
  only:
    - master

notifications:
  email:
    - cjmungall@lbl.gov

